server {
    listen 80;
    server_name cid.tcc.dingols.com.br, tcc.dingols.com.br;
    root /var/www/html/public;

    index index.php index.html;
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
    
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        
        # Mantenha o fix do HTTPS se estiver usando
        fastcgi_param HTTPS on; 

        # --- ADICIONE ISSO AQUI PARA CORRIGIR O ERRO "TOO BIG HEADER" ---
        fastcgi_buffers 16 16k; 
        fastcgi_buffer_size 32k;
        fastcgi_busy_buffers_size 64k; # (Opcional, mas recomendado: buffers + size)
        # ----------------------------------------------------------------
    }
}